In [1]:
import pandas as pd
from nltk.stem import PorterStemmer
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.stem import WordNetLemmatizer
import string
from textblob import TextBlob

In [2]:
data = pd.read_csv("tmdb_action_movies.csv")
data.head(3)

,title,overview,genres,release_date,vote_average,popularity
0,Husbands in Action,A detective teams up with his ex-wife's new hu...,"['Comedy', 'Action']",2026-06-15,7.500,11.9294
1,Back in Action,Fifteen years after vanishing from the CIA to ...,"['Action', 'Comedy']",2025-01-15,6.427,4.6138
2,Action Replayy,A young man tries to revive his parents' wilti...,"['Comedy', 'Romance', 'Science Fiction']",2010-11-05,5.172,2.3793

In [3]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   title         200 non-null    str
 1   overview      188 non-null    str
 2   genres        200 non-null    str
 3   release_date  193 non-null    str
 4   vote_average  200 non-null    float64
 5   popularity    200 non-null    float64
dtypes: float64(2), str(4)
memory usage: 9.5 KB

In [4]:
data.shape

(200, 6)

In [5]:
data.select_dtypes(include=str)

,title,overview,genres,release_date
0,Husbands in Action,A detective teams up with his ex-wife's new hu...,"['Comedy', 'Action']",2026-06-15
1,Back in Action,Fifteen years after vanishing from the CIA to ...,"['Action', 'Comedy']",2025-01-15
2,Action Replayy,A young man tries to revive his parents' wilti...,"['Comedy', 'Romance', 'Science Fiction']",2010-11-05
3,Last Action Hero,"After his father's death, a young boy finds so...","['Fantasy', 'Action', 'Comedy']",1993-06-18
4,A Civil Action,Jan Schlickmann is a cynical lawyer who goes o...,['Drama'],1998-12-25
...,...,...,...,...
195,Re-action,NaN,['Family'],2017-01-01
196,Net of Heaven Action,A CAT III film directed by Patrick Kong Yeung ...,[],1994-01-01
197,First Action Hero,A maverick cop takes on the seedy criminal und...,['Action'],1994-01-01
198,Wolf Killing Action,NaN,"['Action', 'War']",2020-01-05
199,First Aid Action,Concentrates upon basic first aid steps. Simul...,['Documentary'],1973-01-01

In [6]:
data ['title' ] = data['title'].str.lower()

data['overview'] = data['overview'].str.lower()

data['genres'] = data['genres'].str.lower()

In [7]:
data.isnull().sum()

title            0
overview        12
genres           0
release_date     7
vote_average     0
popularity       0
dtype: int64

In [8]:
data[data.isna().any(axis=1)]

,title,overview,genres,release_date,vote_average,popularity
14,action women,NaN,['documentary'],2020-03-10,0.0,1.7121
62,action,exploring transgender and non-binary represent...,[],NaN,0.0,0.0569
69,uppukandam brothers back in action,NaN,['action'],2011-06-11,4.0,1.6216
124,cheetah in action,NaN,"['crime', 'action', 'drama']",1990-01-01,0.0,1.5870
129,action antipub,NaN,[],2013-12-01,0.0,0.1630
130,action 13,NaN,[],2010-01-01,0.0,0.3162
138,nude action,a nude woman dances.,[],NaN,0.0,0.1090
144,bursting action,a rescue team is on a mission to free a girl f...,[],NaN,0.0,0.0584
148,mrs. osei takes action,NaN,"['drama', 'history']",2022-05-11,0.0,0.2612
153,the original action hero,the film will track the evolution of the actio...,"['documentary', 'tv movie']",NaN,0.0,1.0906
154,the action,NaN,[],NaN,0.0,0.1231
166,action! 1987,after an getting into an argument about right ...,[],NaN,0.0,0.4566
167,early action,desperate for their son to gain admission to h...,"['drama', 'comedy']",NaN,0.0,1.1430
169,ready action,NaN,[],2025-01-01,0.0,0.0398
182,53 stages of action,NaN,['drama'],1963-01-23,0.0,0.3487
194,wolves action,NaN,"['action', 'thriller']",2019-11-14,0.0,0.1772
195,re-action,NaN,['family'],2017-01-01,8.2,0.5935
198,wolf killing action,NaN,"['action', 'war']",2020-01-05,0.0,0.2184

In [9]:
data.dropna(inplace=True)

In [10]:
data['genres'].unique()

<StringArray>
[                               '['comedy', 'action']',
                                '['action', 'comedy']',
            '['comedy', 'romance', 'science fiction']',
                     '['fantasy', 'action', 'comedy']',
                                           '['drama']',
          '['action', 'adventure', 'thriller', 'war']',
                   '['animation', 'comedy', 'family']',
                                          '['action']',
                                 '['comedy', 'drama']',
                              '['action', 'thriller']',
                               '['action', 'romance']',
                       '['drama', 'crime', 'history']',
                               '['action', 'western']',
        '['action', 'adventure', 'crime', 'thriller']',
                               '['drama', 'thriller']',
                                        '['thriller']',
                                          '['comedy']',
                                 '['comedy', 'crime']',
                                     '['documentary']',
                                         '['western']',
                                                  '[]',
 '['action', 'comedy', 'science fiction', 'thriller']',
                    '['action', 'crime', 'adventure']',
                    '['comedy', 'action', 'tv movie']',
                              '['action', 'tv movie']',
                      '['romance', 'action', 'drama']',
                                   '['action', 'war']',
                              '['thriller', 'horror']',
            '['action', 'crime', 'drama', 'thriller']',
                     '['crime', 'thriller', 'action']',
                                '['drama', 'romance']',
                                           '['crime']',
       '['action', 'western', 'romance', 'adventure']',
                                 '['drama', 'comedy']',
                      '['drama', 'romance', 'comedy']',
                        '['drama', 'action', 'crime']',
                     '['thriller', 'action', 'crime']',
                           '['comedy', 'documentary']',
                    '['action', 'thriller', 'comedy']',
                '['action', 'drama', 'war', 'comedy']',
                  '['family', 'animation', 'fantasy']',
                       '['drama', 'action', 'comedy']',
                                '['romance', 'drama']',
                        '['documentary', 'adventure']',
                                       '['animation']',
                                         '['romance']',
                                '['drama', 'western']',
                      '['action', 'war', 'adventure']',
                                 '['crime', 'action']',
                                  '['crime', 'drama']',
                       '['science fiction', 'action']',
                              '['comedy', 'thriller']',
                    '['action', 'drama', 'adventure']',
                       '['comedy', 'horror', 'crime']',
                           '['action', 'documentary']',
                                '['crime', 'fantasy']',
                               '['comedy', 'mystery']',
                                 '['science fiction']',
                            '['documentary', 'music']',
                              '['war', 'documentary']',
                       '['action', 'comedy', 'crime']',
                     '['horror', 'thriller', 'drama']',
                              '['documentary', 'war']',
                             '['adventure', 'horror']',
                              '['drama', 'adventure']',
                        '['crime', 'drama', 'action']',
                                 '['action', 'crime']',
                     '['action', 'comedy', 'fantasy']',
              '['action', 'war', 'drama', 'thriller']',
                                             '['war']',
                               '['drama', 'tv movie']',
                  '['tv movie', 'horror', 'thriller']',
                                 '['music', 'action']',
                   '['action', 'family', 'animation']']
Length: 74, dtype: str

In [11]:
def lower_case(sens):
    return sens.lower()

In [12]:
column_string = ", ".join(data.columns)

In [13]:
lower_case(column_string)

'title, overview, genres, release_date, vote_average, popularity'

In [14]:
data

,title,overview,genres,release_date,vote_average,popularity
0,husbands in action,a detective teams up with his ex-wife's new hu...,"['comedy', 'action']",2026-06-15,7.500,11.9294
1,back in action,fifteen years after vanishing from the cia to ...,"['action', 'comedy']",2025-01-15,6.427,4.6138
2,action replayy,a young man tries to revive his parents' wilti...,"['comedy', 'romance', 'science fiction']",2010-11-05,5.172,2.3793
3,last action hero,"after his father's death, a young boy finds so...","['fantasy', 'action', 'comedy']",1993-06-18,6.483,4.6299
4,a civil action,jan schlickmann is a cynical lawyer who goes o...,['drama'],1998-12-25,6.462,2.6111
...,...,...,...,...,...,...
192,hokusotan 2015 (action direct),performance by takashi makino with music compo...,[],2015-05-06,0.000,0.3992
193,animals in action,the profession of capturing animals in action ...,['documentary'],1955-05-21,7.000,0.2973
196,net of heaven action,a cat iii film directed by patrick kong yeung ...,[],1994-01-01,0.000,0.2395
197,first action hero,a maverick cop takes on the seedy criminal und...,['action'],1994-01-01,3.750,0.2112
199,first aid action,concentrates upon basic first aid steps. simul...,['documentary'],1973-01-01,0.000,0.6893

In [15]:
data['overview'][3]

"after his father's death, a young boy finds solace in action movies featuring an indestructible cop. given a magic ticket by a theater manager, he is transported into the film and teams up with the cop to stop a villain who escapes into the real world."

In [16]:
data['word_tokenizer'] = data['overview'].apply(sent_tokenize)

In [22]:
data['word_tokenizer'].apply(' '.join)

0      a detective teams up with his ex-wife's new hu...
1      fifteen years after vanishing from the cia to ...
2      a young man tries to revive his parents' wilti...
3      after his father's death, a young boy finds so...
4      jan schlickmann is a cynical lawyer who goes o...
                             ...
192    performance by takashi makino with music compo...
193    the profession of capturing animals in action ...
196    a cat iii film directed by patrick kong yeung ...
197    a maverick cop takes on the seedy criminal und...
199    concentrates upon basic first aid steps. simul...
Name: word_tokenizer, Length: 182, dtype: str

In [17]:
data['word_tokenizer'][3]

["after his father's death, a young boy finds solace in action movies featuring an indestructible cop.",
 'given a magic ticket by a theater manager, he is transported into the film and teams up with the cop to stop a villain who escapes into the real world.']

In [19]:
data.head(3)

,title,overview,genres,release_date,vote_average,popularity,word_tokenizer
0,husbands in action,a detective teams up with his ex-wife's new hu...,"['comedy', 'action']",2026-06-15,7.500,11.9294,[a detective teams up with his ex-wife's new h...
1,back in action,fifteen years after vanishing from the cia to ...,"['action', 'comedy']",2025-01-15,6.427,4.6138,[fifteen years after vanishing from the cia to...
2,action replayy,a young man tries to revive his parents' wilti...,"['comedy', 'romance', 'science fiction']",2010-11-05,5.172,2.3793,[a young man tries to revive his parents' wilt...